config/routes.rb
Rails.application.routes.draw do
  resources :products
  devise_for :users, controllers: {
        sessions: 'users/sessions', registrations: 'users/registrations'
      }
  root to: "products#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :users, through:  :sales
	has_many :sales
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  	has_many :products, through:  :sales
	has_many :sales
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :autenticate_user!, only: [:edit, :destroy, :new] 

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product =Product.find(params[:id])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :quantity, :description, :picture)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
    def new
      super
    end

  # POST /resource
   def create
     super
   end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chimeras Box</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  	  <nav class="navbar navbar-light bg-faded">
        <a class="navbar-brand" href="/">Chimeras Box</a>
        <ul class="nav navbar-nav">
          
          <%if current_user.nil?%>

            <li>
              <button class="btn btn-danger-outline pull-xs-right" type="submit"><a href="/users/sign_up"> Registrese</a></button>
            </li>

            <li>
              <button class="btn btn-danger-outline pull-xs-right" type="submit"><a href="/users/sign_in"> Log In</a></button>
            </li> 

          <%else%>
            
            <li> 
              <button class="btn btn-danger-outline pull-xs-right" type="submit">
                <%= link_to 'Salir', destroy_user_session_path, method: :delete %>
              </button>
            </li>

            <li>
              <button class="btn btn-danger-outline pull-xs-right" type="submit"><a href="/"> Mi cuenta</a></button>
            </li>

          <%end%>
        </ul>

      </nav> 

    <div class="jumbotron">
      
    </div>

  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  <div class= "container-fluid">
    <div class="row">
      <div class="col-sm-2" id="brands">
        
      </div>

      <div class="col-sm-8" id="yield">
        <%= yield %>
      </div>
    </div>

  </div>
    

  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :quantity %>
    <%= f.number_field :quantity %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :picture %>
    <%= f.text_field :picture %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Productos disponibles en nuestra tienda</h1>

<div class="container">
  <div class="row">
    
    <%@products.each do |product|%>
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
        <div class="card">
          <img src="../assets/<%=product.picture%>" alt="<%=product.picture%>" style="width:100%">
          <div class="container">
            <h4><b><%=product.name%></b></h4> 
            <p><%=product.name%></p>
            <p>Stock: <%=product.quantity%></p>
            <div align="center" >
              <a href="/products/<%=product.id%>" class="btn btn-success btn-sm">Ver</a>
              <br>
            </div>
          </div>
        </div>
      </div>
    <%end%>
  </div>
</div>

<br>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class= "card">

	<img src="../assets/<%=@product.picture%>" alt="<%=@product.picture%>" style="width:100%">

	<div class="container">
	    <h4><b><%=@product.name%></b></h4> 
	    <p><%=@product.name%></p>
	    <h4>Descripcion: </h4>
	    <p><%=@product.description%></p>
	    <p>Stock: <%=@product.quantity%></p>
	    <div align="center" >
	    <a href="" class="btn btn-success btn-sm" id="comprar">Comprar</a>
	    <br>
	</div>
</div>